import 'package:meta/meta.dart';
import 'simulation_state.dart';

/// Represents the output of a single simulation step from the environment's perspective.
///
/// It encapsulates the state vector provided to the agent, the punishment (or error)
/// received, and whether the current episode has concluded.
@immutable
class EnvironmentStep {
  /// The current state of the environment expressed as a vector of doubles.
  final List<double> stateVector;
  /// The punishment or error signal generated by the environment (e.g., TD error).
  final double punishment;
  /// Indicates if the current training or simulation episode has ended.
  final bool isEpisodeEnd;

  const EnvironmentStep({
    required this.stateVector,
    required this.punishment,
    required this.isEpisodeEnd,
  });
}

/// Abstract base class defining the interface for a cerebellar simulation environment.
///
/// Environments provide the sensory inputs (state vector) and reinforcement signals
/// (punishment) that drive the learning process in the cerebellar model.
abstract class CerebellarEnvironment {
  /// The display name of the task (e.g., "Eyeblink Conditioning").
  String get taskName;
  /// The decay constant for eligibility traces in milliseconds, specific to this task.
  double get traceDecayMs;
  /// Advances the environment by a time step [dt], given the current [state].
  ///
  /// Returns an [EnvironmentStep] containing the new state and feedback.
  EnvironmentStep step(SimulationState state, double dt);
  /// Resets the environment to its initial state for a new episode.
  void reset();
}
