import 'package:meta/meta.dart';

/// Represents a single data point used for real-time visualization of the simulation.
///
/// It captures the internal state (prediction), the target external signal,
/// and performance metrics like gain ratio.
@immutable
class PlotPoint {
  /// The predicted signal value generated by the cerebellar model (critic).
  final double criticPrediction;
  /// The actual signal value from the environment (e.g., target head velocity).
  final double actualSignal;
  /// The current performance gain ratio (e.g., eye velocity / head velocity).
  final double gainRatio;

  const PlotPoint({
    required this.criticPrediction,
    required this.actualSignal,
    this.gainRatio = 0.0,
  });
}
